FROM ghcr.io/opentofu/opentofu:1.10-minimal AS tofu

FROM alpine:3.20

COPY --from=tofu /usr/local/bin/tofu /usr/local/bin/tofu

RUN apk add --no-cache gcc musl-dev python3-dev libffi-dev openssl-dev cargo make
RUN python3 -mvenv /usr/local && \
  . /usr/local/bin/activate && \
  python3 -mensurepip --upgrade && \
  python3 -mpip install --upgrade pip && \
  python3 -mpip install azure-cli

WORKDIR /srv/workspace

ENTRYPOINT ["/usr/local/bin/tofu"]
